# site settings
title: Annika Fischer
landing_page_title: Praxis für Osteopathie
seo_landing_page_title: Annika Fischer | Praxis für Osteopathie & Kinderosteopathie
seo_landing_page_description: Osteopathische Behandlung für Erwachsene, Kinder & Babys in Berlin Mitte & Steglitz. Osteopathie MSc, Heilpraktikerin, Mitglied im Osteopathieverband VfO.
baseurl: ""
timezone: Europe/Berlin
lang: de_DE
lang_only: de
theme_color: "#18202a"
last_change:
  privacy_policy: "2. Mai 2023"
  legal: "2. Mai 2023"

# build settings
markdown: kramdown

# page settings
sass:
  style: compressed

google_analytics:
    id: G-MB0KKHMR3K

# plugins
plugins:
  - jekyll-smartify
  - jekyll_version_plugin
  - jekyll-minifier
  - jekyll-webp
  - jekyll-last-modified-at
  - jekyll-sitemap

jekyll-minifier:
  exclude: '**.*'

webp:
  enabled: true
  quality: 80
  img_dir: ["/images"]
  formats: [".jpeg", ".jpg"]
  gifs: [".gif"]
  regenerate: false
  exclude: ["banner.jpg", ".webp"]

# exclude from build
exclude: ["Gemfile", "node_modules", "vendor", "backup", "README.md", "firebase.json", "package.json", "package-lock.json", "fonts/selection.json"]